version: '3'

services: 
  db:
    container_name: my-db22
    ports:
      - 54322:5432
    environment:
      - POSTGRES_USER=natthawut
      - POSTGRES_PASSWORD=peteoly12345
    image: postgres:latest
    restart: 'unless-stopped'
  
  pgadmin:
    container_name: pg-admin122
    ports:
      - 4433:443
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=natthawut-cha@rmutp.ac.th
      - PGADMIN_DEFAULT_PASSWORD=peteoly12345
    image: dpage/pgadmin4:latest
    restart: 'unless-stopped'

  strapi:
    container_name: Natthawut-strapi
    image: naskio/strapi:latest
    ports: 
        - 1337:1337
    environment:
      - name=value
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=192.168.56.1
      - DATABASE_PORT=54322
      - DATABASE_NAME=natthawut
      - DATABASE_USERNAME=natthawut
      - DATABASE_PASSWORD=peteoly12345
      - DATABASE_SSL=false
    restart: 'unless-stopped'
